#!/bin/sh

~/node_modules/.bin/tsc --target es2018 --outDir ../javascript fastrpc.ts
cd ../javascript
mv fastrpc.js fastrpc.mjs
sed -i -e "s/TypeScript/ES2015 (autogenerated from TS source)/" fastrpc.mjs
