/*
FastRPC library written in ES2015 (autogenerated from TS source)
Copyright (C) 2005-2023 Seznam.cz, a.s.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Seznam.cz, a.s.
Radlická 3294/10, Praha 5, 15000, Czech Republic
http://www.seznam.cz, mailto:fastrpc@firma.seznam.cz
*/
const TYPE_CALL = 13;
const TYPE_RESPONSE = 14;
const TYPE_FAULT = 15;
const TYPE_INT = 1;
const TYPE_BOOL = 2;
const TYPE_DOUBLE = 3;
const TYPE_STRING = 4;
const TYPE_DATETIME = 5;
const TYPE_BINARY = 6;
const TYPE_INT8P = 7;
const TYPE_INT8N = 8;
const TYPE_STRUCT = 10;
const TYPE_ARRAY = 11;
const TYPE_NULL = 12;
function isBinary(object) {
    return '_hint' in object && object._hint === 'binary';
}
function isDouble(object) {
    return '_hint' in object && object._hint === 'float';
}
let _hints;
let _path = [];
let _data;
let _pointer = 0;
let _version;
let _arrayBuffers;
export let surrogateFlag = false;
let te = new TextEncoder();
let td = new TextDecoder();
function _parseValue() {
    /* pouzite optimalizace:
     * - zkracena cesta ke konstantam v ramci redukce tecek
     * - posun nejpouzivanejsich typu nahoru
     */
    let first = _getInt(1);
    let type = first >> 3;
    let length, lengthBytes, result, members;
    switch (type) {
        case TYPE_STRING:
            lengthBytes = (first & 7);
            if (_version > 1) {
                lengthBytes++;
            }
            if (!lengthBytes) {
                throw new Error("Bad string size");
            }
            length = _getInt(lengthBytes);
            return _decodeUTF8(length);
            break;
        case TYPE_STRUCT:
            result = {};
            lengthBytes = (first & 7);
            if (_version > 1) {
                lengthBytes++;
            }
            members = _getInt(lengthBytes);
            while (members--) {
                _parseMember(result);
            }
            return result;
            break;
        case TYPE_ARRAY:
            result = [];
            lengthBytes = (first & 7);
            if (_version > 1) {
                lengthBytes++;
            }
            members = _getInt(lengthBytes);
            while (members--) {
                result.push(_parseValue());
            }
            return result;
            break;
        case TYPE_BOOL:
            result = (first & 7);
            if (result > 1) {
                throw new Error(`Invalid bool value ${result}`);
            }
            return !!result;
            break;
        case TYPE_INT:
            length = first & 7;
            if (_version == 3) {
                return _getZigzag(length + 1);
            }
            else {
                if (!length) {
                    throw new Error("Bad int size");
                }
                let max = 0x80000000;
                result = _getInt(length);
                if (result >= max) {
                    result -= max;
                }
                return result;
            }
            break;
        case TYPE_DATETIME:
            _getByte();
            let tsBytes = (_version == 3 ? 8 : 4);
            let ts = _getInt(tsBytes);
            for (let i = 0; i < 5; i++) {
                _getByte();
            }
            return new Date(1000 * ts);
            break;
        case TYPE_DOUBLE:
            return _getDouble();
            break;
        case TYPE_BINARY:
            lengthBytes = (first & 7);
            if (_version > 1) {
                lengthBytes++;
            }
            if (!lengthBytes) {
                throw new Error("Bad binary size");
            }
            length = _getInt(lengthBytes);
            if (_arrayBuffers) {
                let view = new Uint8Array(length);
                for (let i = 0; i < length; i++) {
                    view[i] = _getByte();
                }
                result = view.buffer;
            }
            else {
                result = [];
                while (length--) {
                    result.push(_getByte());
                }
            }
            return result;
            break;
        case TYPE_INT8P:
            length = (first & 7) + 1;
            return _getInt(length);
            break;
        case TYPE_INT8N:
            length = (first & 7) + 1;
            result = _getInt(length);
            return (result ? -result : 0); // no negative zero
            break;
        case TYPE_NULL:
            if (_version > 1) {
                return null;
            }
            else {
                throw new Error("Null value not supported in protocol v1");
            }
            break;
        default:
            throw new Error(`Unknown type ${type}`);
            break;
    }
}
function _append(arr1, arr2) {
    let len = arr2.length;
    for (let i = 0; i < len; i++) {
        arr1.push(arr2[i]);
    }
}
function _parseMember(result) {
    let nameLength = _getInt(1);
    let name = _decodeUTF8(nameLength);
    result[name] = _parseValue();
}
function _getZigzag(bytes) {
    let result = _getInt(bytes);
    let minus = result % 2;
    result = Math.floor(result / 2);
    return (minus ? -1 * (result + 1) : result);
}
/// In little endian
function _getInt(bytes) {
    let result = 0;
    let factor = 1;
    for (let i = 0; i < bytes; i++) {
        result += factor * _getByte();
        factor *= 256;
    }
    return result;
}
function _getByte() {
    if ((_pointer + 1) > _data.length) {
        throw new Error(`Cannot read byte ${_pointer} from buffer`);
    }
    return _data[_pointer++];
}
function _decodeUTF8(length) {
    let ab = new Uint8Array(length);
    for (let i = 0; i < length; i++) {
        ab[i] = _data[_pointer++];
    }
    return td.decode(ab);
}
function _getDouble() {
    let bytes = [];
    let index = 8;
    while (index--) {
        bytes[index] = _getByte();
    }
    let sign = (bytes[0] & 0x80 ? 1 : 0);
    let exponent = (bytes[0] & 127) << 4;
    exponent += bytes[1] >> 4;
    if (exponent === 0) {
        return Math.pow(-1, sign) * 0;
    }
    let mantissa = 0;
    let byteIndex = 1;
    let bitIndex = 3;
    index = 1;
    do {
        let bitValue = (bytes[byteIndex] & (1 << bitIndex) ? 1 : 0);
        mantissa += bitValue * Math.pow(2, -index);
        index++;
        bitIndex--;
        if (bitIndex < 0) {
            bitIndex = 7;
            byteIndex++;
        }
    } while (byteIndex < bytes.length);
    if (exponent == 0x7ff) {
        if (mantissa) {
            return NaN;
        }
        else {
            return Math.pow(-1, sign) * Infinity;
        }
    }
    exponent -= (1 << 10) - 1;
    return Math.pow(-1, sign) * Math.pow(2, exponent) * (1 + mantissa);
}
function _serializeValue(result, value) {
    if (value === null) {
        result.push(TYPE_NULL << 3);
        return;
    }
    switch (typeof (value)) {
        case "string":
            let strData = te.encode(value);
            let intData = _encodeInt(strData.length);
            let first = TYPE_STRING << 3;
            first += (intData.length - 1);
            result.push(first);
            _append(result, intData);
            _append(result, strData);
            break;
        case "number":
            if (_getHint() == "float") {
                _serializeDouble(result, value);
            }
            else { // int
                if (_version == 3) {
                    let data = _encodeZigzag(value);
                    let first = (TYPE_INT << 3) + (data.length - 1);
                    result.push(first);
                    _append(result, data);
                }
                else {
                    let first = (value >= 0 ? TYPE_INT8P : TYPE_INT8N);
                    first = first << 3;
                    let data = _encodeInt(Math.abs(value));
                    first += (data.length - 1);
                    result.push(first);
                    _append(result, data);
                }
            }
            break;
        case "boolean":
            let data = TYPE_BOOL << 3;
            if (value) {
                data += 1;
            }
            result.push(data);
            break;
        case "object":
            if (value instanceof ArrayBuffer) {
                _serializeArrayBuffer(result, value);
            }
            else if (value instanceof Date) {
                _serializeDate(result, value);
            }
            else if (value instanceof Array) {
                if (_getHint() == "binary") {
                    _serializeBinary(result, value);
                }
                else {
                    _serializeArray(result, value);
                }
            }
            else if (isBinary(value)) {
                _serializeBinary(result, value.value);
            }
            else if (isDouble(value)) {
                _serializeDouble(result, value.value);
            }
            else {
                _serializeStruct(result, value);
            }
            break;
        default: // undefined, function, ...
            throw new Error(`FRPC does not allow value ${value}`);
            break;
    }
}
function _serializeArrayBuffer(result, data) {
    let first = TYPE_BINARY << 3;
    let intData = _encodeInt(data.byteLength);
    first += (intData.length - 1);
    result.push(first);
    _append(result, intData);
    _append(result, new Uint8Array(data));
}
function _serializeArray(result, data) {
    let first = TYPE_ARRAY << 3;
    let intData = _encodeInt(data.length);
    first += (intData.length - 1);
    result.push(first);
    _append(result, intData);
    for (let i = 0; i < data.length; i++) {
        _path.push(i.toString());
        _serializeValue(result, data[i]);
        _path.pop();
    }
}
function _serializeBinary(result, data) {
    let first = TYPE_BINARY << 3;
    const intData = _encodeInt(data.length);
    first += (intData.length - 1);
    result.push(first);
    _append(result, intData);
    _append(result, data);
}
function _serializeDouble(result, data) {
    let first = TYPE_DOUBLE << 3;
    let floatData = _encodeDouble(data);
    result.push(first);
    _append(result, floatData);
}
function _serializeStruct(result, data) {
    let numMembers = 0;
    let p;
    for (p in data) {
        numMembers++;
    }
    let first = TYPE_STRUCT << 3;
    let intData = _encodeInt(numMembers);
    first += (intData.length - 1);
    result.push(first);
    _append(result, intData);
    for (let p in data) {
        let strData = te.encode(p);
        result.push(strData.length);
        _append(result, strData);
        _path.push(p);
        _serializeValue(result, data[p]);
        _path.pop();
    }
}
function _serializeDate(result, date) {
    result.push(TYPE_DATETIME << 3);
    // 1 bajt, zona
    let zone = date.getTimezoneOffset() / 15; // pocet ctvrthodin
    if (zone < 0) {
        zone += 256;
    } // dvojkovy doplnek
    result.push(zone);
    // 4/8 bajty, timestamp
    let ts = Math.round(date.getTime() / 1000);
    if (_version == 3) {
        if (ts < 0) { // 64bit -1 neumime v JS zapsat
            _append(result, [0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF]);
        }
        else {
            let tsData = _encodeInt(ts);
            while (tsData.length < 8) {
                tsData.push(0);
            } // do maximalniho poctu bajtu
            _append(result, tsData);
        }
    }
    else {
        if (ts < 0 || ts >= Math.pow(2, 31)) {
            ts = -1;
        }
        if (ts < 0) {
            ts += Math.pow(2, 32);
        } // dvojkovy doplnek
        let tsData = _encodeInt(ts);
        while (tsData.length < 4) {
            tsData.push(0);
        } // do maximalniho poctu bajtu
        _append(result, tsData);
    }
    // 5 bajtu, zbyle haluze
    let year = date.getFullYear() - 1600;
    year = Math.max(year, 0);
    year = Math.min(year, 2047);
    let month = date.getMonth() + 1;
    let day = date.getDate();
    let dow = date.getDay();
    let hours = date.getHours();
    let minutes = date.getMinutes();
    let seconds = date.getSeconds();
    result.push((seconds & 0x1f) << 3 | (dow & 0x07));
    result.push(((minutes & 0x3f) << 1) | ((seconds & 0x20) >> 5) | ((hours & 0x01) << 7));
    result.push(((hours & 0x1e) >> 1) | ((day & 0x0f) << 4));
    result.push(((day & 0x1f) >> 4) | ((month & 0x0f) << 1) | ((year & 0x07) << 5));
    result.push((year & 0x07f8) >> 3);
}
function _encodeZigzag(num) {
    let lastBit = 0;
    if (num < 0) {
        lastBit = 1;
        num *= -1;
    }
    num = 2 * num + lastBit;
    return _encodeInt(num);
}
/**
 * Zakoduje KLADNE cele cislo, little endian
 */
function _encodeInt(data) {
    if (!data) {
        return [0];
    }
    let result = [];
    let remain = data;
    while (remain) {
        let value = remain % 256;
        remain = (remain - value) / 256;
        result.push(value);
    }
    return result;
}
/**
 * Zakoduje IEEE-754 double
 */
function _encodeDouble(num) {
    let result = [];
    let expBits = 11;
    let fracBits = 52;
    let bias = (1 << (expBits - 1)) - 1;
    let sign, exponent, fraction;
    if (isNaN(num)) {
        exponent = (1 << expBits) - 1;
        fraction = 1;
        sign = 0;
    }
    else if (num === Infinity || num === -Infinity) {
        exponent = (1 << expBits) - 1;
        fraction = 0;
        sign = (num < 0 ? 1 : 0);
    }
    else if (num === 0) {
        exponent = 0;
        fraction = 0;
        sign = (1 / num === -Infinity ? 1 : 0);
    }
    else { /* normal number */
        sign = num < 0;
        let abs = Math.abs(num);
        if (abs >= Math.pow(2, 1 - bias)) {
            let ln = Math.min(Math.floor(Math.log(abs) / Math.LN2), bias);
            exponent = ln + bias;
            fraction = abs * Math.pow(2, fracBits - ln) - Math.pow(2, fracBits);
        }
        else {
            exponent = 0;
            fraction = abs / Math.pow(2, 1 - bias - fracBits);
        }
    }
    let bits = [];
    for (let i = fracBits; i > 0; i--) {
        bits.push(fraction % 2 ? 1 : 0);
        fraction = Math.floor(fraction / 2);
    }
    for (let i = expBits; i > 0; i--) {
        bits.push(exponent % 2 ? 1 : 0);
        exponent = Math.floor(exponent / 2);
    }
    bits.push(sign ? 1 : 0);
    num = 0;
    let index = 0;
    while (bits.length) {
        num += (1 << index) * bits.shift();
        index++;
        if (index == 8) {
            result.push(num);
            num = 0;
            index = 0;
        }
    }
    return result;
}
/**
 * Vrati aktualni hint, na zaklade "_path" a "_hints"
 * @returns {string || null}
 */
function _getHint() {
    if (!_hints) {
        return null;
    }
    if (typeof (_hints) != "object") {
        return _hints;
    } // skalarni varianta
    return _hints && _hints[_path.join(".")];
}
/**
 * @param {string} method
 * @param {?} data
 * @param {object} hints hinty, ktera cisla maji byt floaty a kde jsou binarni data (klic = cesta, hodnota = "float"/"binary")
 * @returns {BYTES}
 */
export function serialize(data, hints, options) {
    let result = [];
    _path = [];
    _hints = hints;
    _version = (options && options.version) || 2;
    _serializeValue(result, data);
    _hints = undefined;
    return result;
}
/**
 * @param {string} method
 * @param {array} data
 * @param {object || string} hints Napoveda datovych typu:
 * pokud string, pak typ (skalarni) hodnoty "data". Pokud objekt,
 * pak mnozina dvojic "cesta":"datovy typ"; cesta je teckami dodelena posloupnost
 * klicu a/nebo indexu v datech. Typ je "float" nebo "binary".
 * @param {options}
 */
export function serializeCall(method, data, hints, options) {
    let result = serialize(data, hints, options);
    // utrhnout hlavicku pole (dva bajty)
    result.shift();
    result.shift();
    let encodedMethod = te.encode(method);
    result.unshift.apply(result, encodedMethod);
    result.unshift(encodedMethod.length);
    result.unshift(TYPE_CALL << 3);
    let major = _version;
    let minor = (_version == 2 ? 1 : 0);
    result.unshift(0xCA, 0x11, major, minor);
    return result;
}
/**
 * @param {BYTES} data
 * @returns {object}
 */
export function parse(data, options) {
    _arrayBuffers = (options && options.arrayBuffers) || false;
    surrogateFlag = false;
    _pointer = 0;
    _data = data;
    let magic1 = _getByte();
    let magic2 = _getByte();
    if (magic1 != 0xCA || magic2 != 0x11) {
        _data = new Uint8Array();
        throw new Error("Missing FRPC magic");
    }
    _version = _getByte();
    _getByte(); // minor
    let first = _getInt(1);
    let type = first >> 3;
    if (type == TYPE_FAULT) {
        let num = _parseValue();
        let msg = _parseValue();
        _data = new Uint8Array();
        throw new Error("FRPC/" + num + ": " + msg);
    }
    let result;
    switch (type) {
        case TYPE_RESPONSE:
            result = _parseValue();
            if (_pointer < _data.length) {
                _data = new Uint8Array();
                throw new Error("Garbage after FRPC data");
            }
            break;
        case TYPE_CALL:
            let nameLength = _getInt(1);
            let name = _decodeUTF8(nameLength);
            if (!name.length) {
                throw new Error("Method name is an empty string");
            }
            let params = [];
            while (_pointer < _data.length) {
                params.push(_parseValue());
            }
            _data = new Uint8Array();
            return { method: name, params: params };
            break;
        default:
            _data = new Uint8Array();
            throw new Error("Unsupported TYPE " + type);
            break;
    }
    _data = new Uint8Array();
    return result;
}
